### ISSUE TITLE
Fatal error: Call to undefined function has_wp_user_avatar()

### ISSUE THREAD

**Issue by justinngc** [emcconne/surfagility#1]
Error: http://otwieraczumyslow.pl/author/piotrek/

Is this a native WP function? A few websites I visited had this error, including to my own install.

**Comment by Pepenix** [comment]
I have no idea i just wanted to have theme similar to medium. But since surfagility has text column on the right because of the author column being on the left I asked friend to try to fix this. So she deleted the avatar on post to be able to center text column. I presume its because of that i get error.

**Comment by emcconne** [comment]
I'll take a look at it today.

**Comment by emcconne** [comment]
Fixed in master.  WP User Avatar plugin should no longer be required to display properly.

**Comment by Pepenix** [comment]
Great!

Im new to github and i cant find place to talk to you so i sorry talking thru email. But i have a question.

Where can i change fonts? Because the standard one doesnt display polish signs properly.
Can you do some custiomization work for payment if i wanted to customize your theme for my blog?

Piotr Poznański
Cogitus Akademia Rozwoju Umysłu

**Comment by emcconne** [comment]
The theme really isn't designed for internationalization at this point.  I'd need to create translation strings which I don't really have the time to do just now.  If you want to change the font change it in less/surfagility.less.  Changing the 2 variables at the top of the file, @font_family, @heading_font_family, will change it throughout.
